<?php

// This is a template file to be used for loading extra translation strings into OpenConf
//
// INSTRUCTIONS:
//
// Make a copy of the file and call it extras.inc
// Replace *** in the first code line below with the language encoding found in the locale.inc file for the desired language (e.g., es, fr, pt-BR)
// Add translation pairs using the format below, with one pair per line
//     Single-quotes within a string must be prefixed by a backslash ( \' ), and smart-quotes are best avoided
// Move the extras.inc file you created into the openconf/lib/locale/*** directory

$OC_translationExtrasAR['***'] = array(
	'original string' => 'translated string',
);

