<?php

// +----------------------------------------------------------------------+
// | OpenConf                                                             |
// +----------------------------------------------------------------------+
// | Copyright (c) 2002-2024 Zakon Group LLC.  All Rights Reserved.       |
// +----------------------------------------------------------------------+
// | This source file is subject to the OpenConf License, available on    |
// | the OpenConf web site: www.OpenConf.com                              |
// +----------------------------------------------------------------------+

if (!defined('OC'.'C_LICE'.'NSE_TYPE') || !preg_match("/Brand/i",constant('OC'.'C_LICE'.'NSE_TYPE'))) {
	print '
	
<script>oc_' . 'ch' . 'eck' . 'B' . '();</script>
';
}
